default:
  tags:
    - docker
  image: gradle:jdk21-noble

stages:
  - build
  - Testing
  - DeployDocs

java-build:
  image: maven:3.8-openjdk-11
  stage: build
  script:
    - mvn package -D skipTests=true

test:
  stage: Testing
  script:
    - mvn test

pages:
  stage: DeployDocs
  script:
    - mkdir -p public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public
