default:
  tags:
    - docker
  image: gradle:jdk21-noble

stages:
  - Testing
  - DeployDocs

test:
  stage: Testing
  script:
    - tests/test.sh
    - tests/jar.sh

pages:
  stage: DeployDocs
  script:
    - mkdir -p public
    - cp -r docs/* public/
  artifacts:
    paths:
      - public
